# Generated by Django 3.0 on 2020-07-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_customuseradmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('L', 'Lab'), ('F', 'Field')], max_length=15),
        ),
    ]
