# Generated by Django 3.0 on 2020-07-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200726_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Lab', 'Lab'), ('Field', 'Field')], max_length=15),
        ),
    ]
