# Generated by Django 3.0 on 2020-07-26 14:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('civilID', models.CharField(max_length=25)),
                ('civilSerial', models.CharField(max_length=25)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('first', models.CharField(max_length=25)),
                ('last', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('resultDate', models.DateTimeField(blank=True, null=True)),
                ('testNotes', models.TextField()),
                ('testResult', models.NullBooleanField(choices=[(None, ''), (True, 'Yes'), (False, 'No')], default=None, max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
