# Generated by Django 3.0 on 2020-08-22 16:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Created Date')),
                ('civil_ID', models.CharField(max_length=25, unique=True, verbose_name='Civil ID')),
                ('civil_serial', models.CharField(blank=True, max_length=25, null=True, verbose_name='Civil ID Serial')),
                ('passport_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Passport Number')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('city', models.CharField(blank=True, max_length=25, null=True, verbose_name='City')),
                ('nationality', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nationality')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, verbose_name='Gender')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('first_name', models.CharField(max_length=25, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last Name')),
                ('comments', models.TextField(blank=True, max_length=700, null=True, verbose_name='Comments')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'ordering': ['-created_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestingCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False)),
                ('qr_code', models.ImageField(blank=True, upload_to='')),
                ('mixed', models.CharField(blank=True, choices=[('False', 'False'), ('True', 'True')], default='False', max_length=10, null=True, verbose_name='Mixed')),
                ('symptoms', models.CharField(blank=True, choices=[('False', 'False'), ('True', 'True')], default='False', max_length=10, null=True, verbose_name='Covid Symptoms')),
                ('test_result', models.CharField(blank=True, choices=[(None, ''), ('Positive', 'Positive'), ('Negative', 'Negative'), ('Equivalent', 'Equivalent'), ('Reject', 'Reject')], default=None, max_length=10, null=True, verbose_name='Test Result')),
                ('test_notes', models.TextField(blank=True, null=True, verbose_name='Test Notes')),
                ('sms_status', models.BooleanField(blank=True, default=False, null=True, verbose_name='SMS Sent')),
                ('result_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Result Date')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('sample_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Sample Date')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('field_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_user', to=settings.AUTH_USER_MODEL, verbose_name='Field User')),
                ('lab_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_doctor', to=settings.AUTH_USER_MODEL, verbose_name='Lab Doctor')),
                ('lab_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_user', to=settings.AUTH_USER_MODEL, verbose_name='Lab User')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_tests', to='pages.Patient', verbose_name='Patient Civil ID')),
                ('screening_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screeningcenter_tests', to='pages.ScreeningCenter', verbose_name='Screening Center')),
                ('testing_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testingcenter_tests', to='pages.TestingCenter', verbose_name='Testing Center')),
            ],
            options={
                'ordering': ['-sample_datetime'],
            },
        ),
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created Data time')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=200)),
                ('sent_status', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_smses', to='pages.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Patient')),
                ('testing_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.TestingCenter')),
            ],
        ),
    ]
