# Generated by Django 3.0 on 2020-08-03 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200802_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='sample_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Sample Date'),
        ),
    ]
