# Generated by Django 3.0 on 2020-07-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200728_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
        migrations.AddField(
            model_name='patient',
            name='mixed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Mixed'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.BooleanField(blank=True, null=True, verbose_name='Covid Symptoms'),
        ),
    ]
