# Generated by Django 3.0 on 2020-07-26 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200726_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='pages.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='test',
            name='testResult',
            field=models.NullBooleanField(choices=[(None, ''), (True, 'Positive'), (False, 'Negative')], default=None, max_length=3, verbose_name='Test Result'),
        ),
    ]
