# Generated by Django 3.0 on 2020-07-29 13:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0004_auto_20200729_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='startTime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='testingCenter',
            new_name='testing_center',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='civilID',
            new_name='civil_ID',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='civilSerial',
            new_name='civil_serial',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='resultDate',
            new_name='result_datetime',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='smsStatus',
            new_name='sms_status',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='testNotes',
            new_name='test_notes',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='testResult',
            new_name='test_result',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='testingCenter',
            new_name='testing_center',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mixed',
        ),
        migrations.RemoveField(
            model_name='test',
            name='author',
        ),
        migrations.RemoveField(
            model_name='test',
            name='datatime',
        ),
        migrations.RemoveField(
            model_name='test',
            name='lastModified',
        ),
        migrations.AddField(
            model_name='patient',
            name='passport_number',
            field=models.CharField(default=None, max_length=25, verbose_name='Passport Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='created_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Created Date'),
        ),
        migrations.AddField(
            model_name='test',
            name='field_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='field_user', to=settings.AUTH_USER_MODEL, verbose_name='Field'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='lab_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lab_user', to=settings.AUTH_USER_MODEL, verbose_name='Lab'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='mixed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Mixed'),
        ),
        migrations.AddField(
            model_name='test',
            name='sampling_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Samping Date'),
        ),
        migrations.AddField(
            model_name='test',
            name='symptoms',
            field=models.BooleanField(blank=True, null=True, verbose_name='Covid Symptoms'),
        ),
        migrations.AddField(
            model_name='test',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.TextField(blank=True, default=False, max_length=250, verbose_name='Symptoms'),
            preserve_default=False,
        ),
    ]
