# Generated by Django 3.0 on 2020-08-04 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200803_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsnotification',
            name='datatime',
        ),
        migrations.RemoveField(
            model_name='smsnotification',
            name='sent_timestamp',
        ),
        migrations.RemoveField(
            model_name='smsnotification',
            name='user',
        ),
        migrations.AddField(
            model_name='smsnotification',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Data time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsnotification',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
