# Generated by Django 3.0 on 2020-07-26 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200726_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_tests', to='pages.Patient', verbose_name='Patient'),
        ),
    ]
