# Generated by Django 3.0 on 2020-07-29 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0005_auto_20200729_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='civil_serial',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Civil ID Serial'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='passport_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Passport Number'),
        ),
        migrations.AlterField(
            model_name='test',
            name='lab_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_user', to=settings.AUTH_USER_MODEL, verbose_name='Lab'),
        ),
        migrations.AlterField(
            model_name='test',
            name='mixed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Mixed'),
        ),
        migrations.AlterField(
            model_name='test',
            name='symptoms',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Covid Symptoms'),
        ),
    ]
