# Generated by Django 3.0 on 2020-07-29 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0006_auto_20200729_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='field_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_user', to=settings.AUTH_USER_MODEL, verbose_name='Field User'),
        ),
        migrations.AlterField(
            model_name='test',
            name='lab_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_user', to=settings.AUTH_USER_MODEL, verbose_name='Lab User'),
        ),
    ]
