# Generated by Django 3.0 on 2020-07-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_patient_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='mixed',
            field=models.CharField(blank=True, default='False', max_length=10, null=True, verbose_name='Mixed'),
        ),
        migrations.AlterField(
            model_name='test',
            name='symptoms',
            field=models.CharField(blank=True, default='False', max_length=10, null=True, verbose_name='Covid Symptoms'),
        ),
    ]
