# Generated by Django 3.0 on 2020-07-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_test_lab_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
