# Generated by Django 3.0 on 2020-07-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20200729_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
