# Generated by Django 3.0 on 2020-07-30 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20200730_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='screening_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screeningcenter_tests', to='pages.ScreeningCenter', verbose_name='Screening Center'),
        ),
        migrations.AlterField(
            model_name='test',
            name='testing_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testingcenter_tests', to='pages.TestingCenter', verbose_name='Testing Center'),
        ),
    ]
